---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acm-operator-deployment
spec:
  project: default
  source:
    repoURL: https://github.com/suulperi/homelab.git 
    targetRevision: HEAD
    path: gitops/acm/instance
  destination:
    server: "https://kubernetes.default.svc"
    namespace: open-cluster-management
  syncPolicy:
    automated:
      allowEmpty: true