---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-operator-deployment
spec:
  project: default
  source:
    repoURL: https://github.com/suulperi/homelab.git 
    targetRevision: HEAD
    path: gitops/metallb/operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: metallb-system
  syncPolicy:
    automated:
      allowEmpty: true